---
#https://access.redhat.com/solutions/4566711
- name: Patch AAP nodes
  hosts: "{{aap_nodes}}"
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Include vars based on OS major version
      include_vars:
        file: vars/el{{ansible_distribution_major_version}}/el{{ansible_distribution_major_version}}_pkgs.yml
        name: exclude_list

    - name: Update all packages except those who are in the exclude list
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude: exclude_list